name: CICD Pipeline

on: 
  push:
    branches:
      - main 
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          ls -lrt ../../yii2-app/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest ../../yii2-app/
          docker push ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker service update --image ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest yii2_yii2-app || \
            docker stack deploy -c /home/ubuntu/some-path/swarm/deploy.yml yii2
