name: CICD Pipeline

on: 
  push:
    branches:
      - main 
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH private key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yaml --private-key ~/.ssh/id_rsa -u ubuntu
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest -f yii2-app/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/yii2-app
            docker pull $IMAGE:deploying

            if docker service inspect yii2_yii2-app > /dev/null 2>&1; then
              docker service update --image $IMAGE:deploying yii2_yii2-app
            else
              docker tag $IMAGE:deploying $IMAGE:latest
              docker stack deploy -c /home/ubuntu/docker-swarm/deploy.yaml yii2
            fi

            echo "Waiting 10 seconds for the service to stabilize..."
            sleep 10

            echo "Performing health check..."
            if ! curl -fs http://localhost > /dev/null; then
              echo "Health check failed. Rolling back..."
              docker service rollback yii2_yii2-app || true
              exit 1
            fi

            echo "Health check passed. Tagging as stable."
            docker tag $IMAGE:deploying $IMAGE:stable
            docker push $IMAGE:stable

      - name: Check NGINX & Docker status
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl status nginx
            docker service ls
            curl -I localhost
